# environment variables for any dev environment
version: '3.1'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  mongo-server:
    image: "bitnami/mongodb:4.0.6"
    ports:
      - "27017:27017"

  rabbitmq:
    image: "rabbitmq:3.7-management-alpine"
    ports:
      - "5672:5672" # web port
      - "15672:15672" # web management port
